spring.application.name=employee-management-system
spring.profiles.active=local
# spring.config.import=optional:application-secret.properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
