spring.application.name=employee-management-system

# Default profile (can be overridden via system property -Dspring.profiles.active=prod or ENV SPRING_PROFILES_ACTIVE=prod)
spring.profiles.active=local
